<a href="https://colab.research.google.com/github/NandikaPrapanca/data-mining/blob/main/preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
dataset = pd.read_csv('random_data.csv', delimiter=';')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [ ]:
print(x)

[['Germany' 28.0 77612.0]
 ['Portugal' 49.0 43817.0]
 ['Portugal' 44.0 84420.0]
 ['Portugal' 41.0 nan]
 ['Germany' 40.0 57423.0]
 ['Spain' nan 73403.0]
 ['Italy' 49.0 63883.0]
 ['Portugal' 55.0 47932.0]
 ['Italy' 50.0 88944.0]
 ['Spain' 50.0 65276.0]]


In [ ]:
print(y)

['Yes' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [ ]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
x[:, 1:3] = imputer.fit_transform(x[:, 1:3].astype(float))
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [ ]:
print(x)

[['Germany' 28.0 77612.0]
 ['Portugal' 49.0 43817.0]
 ['Portugal' 44.0 84420.0]
 ['Portugal' 41.0 66967.77777777778]
 ['Germany' 40.0 57423.0]
 ['Spain' 45.111111111111114 73403.0]
 ['Italy' 49.0 63883.0]
 ['Portugal' 55.0 47932.0]
 ['Italy' 50.0 88944.0]
 ['Spain' 50.0 65276.0]]


In [ ]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [ ]:
print(x)

[[1.0 0.0 0.0 0.0 28.0 77612.0]
 [0.0 0.0 1.0 0.0 49.0 43817.0]
 [0.0 0.0 1.0 0.0 44.0 84420.0]
 [0.0 0.0 1.0 0.0 41.0 66967.77777777778]
 [1.0 0.0 0.0 0.0 40.0 57423.0]
 [0.0 0.0 0.0 1.0 45.111111111111114 73403.0]
 [0.0 1.0 0.0 0.0 49.0 63883.0]
 [0.0 0.0 1.0 0.0 55.0 47932.0]
 [0.0 1.0 0.0 0.0 50.0 88944.0]
 [0.0 0.0 0.0 1.0 50.0 65276.0]]


In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[1 1 1 1 0 1 0 1 0 1]


In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=1)

In [ ]:
print(x_train)

[[0.0 1.0 0.0 0.0 49.0 63883.0]
 [1.0 0.0 0.0 0.0 40.0 57423.0]
 [1.0 0.0 0.0 0.0 28.0 77612.0]
 [0.0 0.0 1.0 0.0 41.0 66967.77777777778]
 [0.0 0.0 1.0 0.0 49.0 43817.0]
 [0.0 0.0 1.0 0.0 55.0 47932.0]
 [0.0 1.0 0.0 0.0 50.0 88944.0]
 [0.0 0.0 0.0 1.0 45.111111111111114 73403.0]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 0.0 44.0 84420.0]
 [0.0 0.0 0.0 1.0 50.0 65276.0]]


In [ ]:
print(y_train)

[0 0 1 1 1 1 0 1]


In [ ]:
print(y_test)

[1 1]


In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [ ]:
print(x_train)

[[0.0 1.0 0.0 -0.3779644730092272 0.5595485842272204 -0.07868628989069082]
 [1.0 0.0 0.0 -0.3779644730092272 -0.5951886214391444 -0.5346863790254806]
 [1.0 0.0 0.0 -0.3779644730092272 -2.1348382289942975 0.8904197818943754]
 [0.0 0.0 1.0 -0.3779644730092272 -0.46688448747621497 0.1390627722807777]
 [0.0 0.0 1.0 -0.3779644730092272 0.5595485842272204 -1.495110096172222]
 [0.0 0.0 1.0 -0.3779644730092272 1.3293733880047969 -1.2046394511583427]
 [0.0 1.0 0.0 -0.3779644730092272 0.6878527181901498 1.6903258206057434]
 [0.0 0.0 0.0 2.6457513110645903 0.06058806326027304 0.5933138414658414]]


In [ ]:
print(x_test)

[[0.0 0.0 1.0 -0.3779644730092272 -0.08197208558742673 1.3709845817132065]
 [0.0 0.0 0.0 2.6457513110645903 0.6878527181901498 0.01964314109456646]]
